{
 "title": "Home Power Usage",
 "time": { "from": "now-8d/d", "to": "now-1d/d" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "STD_kwH", "label": "€ / kWh (STD)", "query": "${VAR_STD_KWH}" },
   { "name": "HC_kwH", "label": "€ / kWh (HC)", "query": "${VAR_HC_KWH}" },
   { "name": "HP_kwH", "label": "€ / kWh (HP)", "query": "${VAR_HP_KWH}" }
  ]
 },
 "panels": [
  {
   "title": "Consommation Heures Pleines",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "heures_creuses", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Heures Pleines ($HP_kwH€/kWh/6k)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 0 },
   "format": "currencyEUR",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "query": "SELECT sum(\"value\")  / 1000 * $HP_kwH  FROM \"conso_elec\" WHERE  (\"heures_creuses\" = '0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "heures_creuses", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Répartition HC/HP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"conso_elec\" WHERE $timeFilter AND heures_creuses = '1' GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "query": "SELECT sum(\"value\") FROM \"conso_elec\" WHERE $timeFilter AND heures_creuses = '0' GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consommation Heures Creuses",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 3 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "heures_creuses", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Heures Creuses ($HC_kwH€/kWh/6k)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 3 },
   "format": "currencyEUR",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "query": "SELECT sum(\"value\")  / 1000 * $HC_kwH  FROM \"conso_elec\" WHERE  (\"heures_creuses\" = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Period",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 6 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures Normales ($STD_kwH€/kWh/6k)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 6 },
   "format": "currencyEUR",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "query": "SELECT sum(\"value\")  / 1000 * $STD_kwH FROM \"conso_elec\" WHERE  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Consumption - in (k)Wh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Heures pleinnes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"conso_elec\" WHERE (\"heures_creuses\" = '0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heures creuses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"conso_elec\" WHERE (\"heures_creuses\" = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "heures_creuses", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption Values per 30min",
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "alias": "Power Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Consumption - per Day (k)Wh",
   "type": "graph",
   "gridPos": { "h": 16, "w": 19, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Watt/Day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "query": "SELECT sum(\"value\") FROM \"conso_elec\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Paris')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "heures_normales", "operator": "=", "value": "0" }
     ]
    }
   ]
  }
 ]
}